#include "include/LoginWindow.h"
#include "ui_LoginWindow.h" // generated by uic; ensure moc runs
#include "include/UserManager.h"
#include <QMessageBox>
#include <QSqlQuery>
#include <QVariant>

LoginWindow::LoginWindow(QWidget *parent) :
    QDialog(parent),
    ui(new Ui::LoginWindow)
{
    ui->setupUi(this);
    connect(ui->btnLogin, &QPushButton::clicked, this, &LoginWindow::onLogin);
    connect(ui->btnRegister, &QPushButton::clicked, this, &LoginWindow::onRegister);
}

LoginWindow::~LoginWindow()
{
    delete ui;
}

void LoginWindow::onLogin()
{
    QString user = ui->editUsername->text().trimmed();
    QString pass = ui->editPassword->text();

    if (user.isEmpty() || pass.isEmpty()) {
        QMessageBox::warning(this, "Input", "Enter username and password.");
        return;
    }

    int id = UserManager::loginUser(user, pass);
    if (id > 0) {
        m_userId = id;
        accept();
    } else {
        QMessageBox::warning(this, "Login Failed", "Invalid username or password.");
    }
}

void LoginWindow::onRegister()
{
    QString user = ui->editUsername->text().trimmed();
    QString pass = ui->editPassword->text();

    if (user.isEmpty() || pass.isEmpty()) {
        QMessageBox::warning(this, "Input", "Enter username and password to register.");
        return;
    }

    if (UserManager::registerUser(user, pass)) {
        QMessageBox::information(this, "Registered", "User registered. You can now log in.");
    } else {
        QMessageBox::warning(this, "Register Failed", "Could not register user. Username might be taken.");
    }
}
